import active_imitation.agents.mujoco_robot
from active_imitation.agents.mujoco_robot import GymRobotAgent
from active_imitation.agents.classic_gym import GymAgent
from active_imitation.agents.atari_gym import AtariGymAgent
